
project_id = "tkwffswlgpzxyyuhdrrp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 10000

[graphql]
enabled = true
port = 54329

[inbound_email]
enabled = false

[db]
port = 54322

[functions.test-profile-image]
verify_jwt = false

[functions.whatsapp-webhook-v3]
verify_jwt = false

[functions.migrate-profile-images]
verify_jwt = false

[functions.scanner-relay]
verify_jwt = false

[functions.retry-failed-messages]
verify_jwt = true

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54324
