
project_id = "tkwffswlgpzxyyuhdrrp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 10000

[db]
port = 54322

[functions.test-profile-image]
verify_jwt = false

[functions.whatsapp-webhook-v3]
verify_jwt = false

[functions.migrate-profile-images]
verify_jwt = false

[functions.scanner-relay]
verify_jwt = false

[functions.retry-failed-messages]
verify_jwt = true

[functions.send-redemption-code]
verify_jwt = true

[functions.track-carrier]
verify_jwt = true

[functions.refresh-carrier-tracking]
verify_jwt = true

[functions.cron-carrier-tracking]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = true

[functions.whatsapp-upload-and-send-media]
verify_jwt = true

[functions.whatsapp-download-media]
verify_jwt = true

[realtime]
enabled = true

[studio]
enabled = true
port = 54324
