
project_id = "tkwffswlgpzxyyuhdrrp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-manual-message]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.create-chat-storage]
verify_jwt = false
