// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnuahsuehizwwcejqilm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJudWFoc3VlaGl6d3djZWpxaWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzY4OTYsImV4cCI6MjA2NDI1Mjg5Nn0.fJL0agNHUI7AK4ReM_bPJECk3DfCKNKpRSApApTqR48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);